import React from 'react';
import { connect } from 'react-redux'
import { addTodo } from '../actions/actions'

let AddTodo = ({ dispatch }) => {
    let input;
    return (
      //Wrapping into <div> because a component needs to have a single root element
      <div> 
        <input 
          ref={node =>{ input = node; }} 
          onKeyPress={
              (e) => {
                 if (e.key === 'Enter') {
                  dispatch(addTodo(input.value))  
                  input.value = '';
                }
          }
        }
          />
          <button onClick={() => {
            dispatch(addTodo(input.value))
              input.value = '';
            }}>
            Add Todo
          </button>
        </div>
    );
   };
   //reassign it now so that the consuming component does not need to specify the dispatch prop 
   //because it will be injected by the component generated by the connect code.
  AddTodo = connect()(AddTodo);

  export default AddTodo;